name: blog_app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.0
      - name: Bundle install
        run: |
          gem install bundler
          bundle install
      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
      - name: Run RSpec
        run: COVERAGE=true bundle exec rspec --require rails_helper
        env:
          RAILS_ENV: test
