name: blog_app

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog-db-test
    env:
      RAILS_ENV: test
      # DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@latest
        with:
          bundler-cache: true
          ruby-version: 3.0.0
      - name: Setup Database schema
        run: bin/rails db:schema:load
      - name: Run RSpec
        run: bin/rake
